### ISSUE TITLE
Alignment of Title to Body

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Systems/web#12]
![image](https://user-images.githubusercontent.com/26971036/97144192-667de200-173a-11eb-8f6a-42694bd9ecaf.png)

You can see the body is flush to the border but the same is not true for the titles. We need to make sure this is consistent since it looks very off now.

**Comment by BrandonLucasZhu** [comment]
What do you mean by flush? The alignment is not consistent?

**Comment by cSDes1gn** [comment]
> What do you mean by flush? The alignment is not consistent?

Yea the body is left-aligned but the header is almost center-aligned. It looks weird to me

**Comment by BrandonLucasZhu** [comment]
They're both left aligned according to the console. I think I just need to remove the margins and padding and should be aligned.

**Comment by cSDes1gn** [comment]
Ok sounds good. Also for responsive the separation between the card bodies should be some set width.
