### ISSUE TITLE
Link Coloration

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Systems/web#14]
<img width="1010" alt="Screen Shot 2020-10-31 at 10 21 19 AM" src="https://user-images.githubusercontent.com/26971036/97781597-f5d42c80-1b62-11eb-8fc5-60c1b3f0ce56.png">

The text for the link is blended into the background. I think it should be a link with the same font as the body. Its not 100% intuitive to click the image to visit the link

**Comment by BrandonLucasZhu** [comment]
When you hover over it, I can make it purple like the nav-bar.

**Comment by cSDes1gn** [comment]
Well you cant see the link to begin with :p
