### ISSUE TITLE
Fix Resizing

### ISSUE THREAD

**Issue by cSDes1gn** [LEAP-Systems/web#5]
![image](https://user-images.githubusercontent.com/26971036/97069081-6dbab980-159b-11eb-9ea8-596e649b225a.png)

Depending on the page size the media can appear super stretched or super squeezed. We want to make the rendering consistent across all devices and display sizes

**Comment by BrandonLucasZhu** [comment]
It's not fully responsive yet. I was testing just the general outlook to get your initial opinion on the title page. When we finalize a welcome page design, then I will add responsive capabilities.

**Comment by cSDes1gn** [comment]
ok I think the cube graphic can be moved somewhere else. Its too small on the front page

**Comment by BrandonLucasZhu** [comment]
Might need to reword a lot of the design that i've implemented. I have a temporary responsive solution at the moment.
